test:
  adapter: postgresql
  database: playola_test
  encoding: unicode
  host: localhost

development:
  adapter: postgresql
  database: playola_development
  encoding: unicode
  host: localhost

# production:
#   adapter: postgresql
#   database: playola
#   encoding: unicode
#   host: localhost